# Generated by Django 4.1.3 on 2023-03-21 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_salary', models.BigIntegerField()),
                ('address', models.TextField(max_length=400)),
                ('created_now', models.DateTimeField(default=datetime.datetime(2023, 3, 21, 13, 3, 23, 964930))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.department')),
            ],
        ),
    ]
