# Generated by Django 4.1.3 on 2023-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvtouser', '0002_alter_userinfo_birthday_alter_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(max_length=100),
        ),
    ]
